version: "3.8"

x-common: &common
  image: ghcr.io/opentensor/subtensor:latest
  cpu_count: 4
  mem_limit: 40000000000
  memswap_limit: 80000000000
  ports:
    - "9944:9944"
    - "30333:30333"
    - "9933:9933"
  expose:
    - "9944"
    - "30333"
    - "9933"
  environment:
    - CARGO_HOME=/var/www/node-subtensor/.cargo

services:
  validator:
    image: thebes1618/affine:latest
    container_name: affine-validator
    restart: unless-stopped
    mem_reservation: "6g"
    mem_limit:       "8g"
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env:ro
      - ~/.bittensor/wallets:/root/.bittensor/wallets:ro
      - validator-cache:/app/data/blocks
    ports:
      - "8001:8000"           # host 8001 → container’s AFFINE_METRICS_PORT=8000
    environment:
      - AFFINE_CACHE_DIR=/app/data/blocks
      - AFFINE_METRICS_PORT=8000
      - AFFINE_METRICS_ADDR=0.0.0.0
    command: ["-vv", "validate"]

  runner:
    image: thebes1618/affine:latest
    container_name: affine-runner
    restart: unless-stopped
    mem_reservation: "6g"
    mem_limit:       "8g"
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env:ro
      - ~/.bittensor/wallets:/root/.bittensor/wallets:ro
      # runner doesn’t need the cache—omit or give its own if desired
    ports:
      - "8002:8000"           # host 8002 → container’s AFFINE_METRICS_PORT=8000
    environment:
      - AFFINE_METRICS_PORT=8000
      - AFFINE_METRICS_ADDR=0.0.0.0
    command: ["-vv", "runner"]

  prometheus:
    image: prom/prometheus:latest
    container_name: affine-prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    command:
      - "--config.file=/prometheus/prometheus.yml"
      - "--log.level=warn"

  grafana:
    image: grafana/grafana:latest
    container_name: affine-grafana
    restart: unless-stopped
    ports:
      - "8000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_HTTP_ADDR=0.0.0.0
      - GF_LOG_LEVEL=warn       
      - GF_LOG_MODE=console     
    volumes:
      - grafana-storage:/var/lib/grafana:rw

  mainnet-lite:
    <<: *common
    container_name: subtensor-mainnet-lite
    volumes:
      - mainnet-lite-volume:/data
    environment:
      - RUST_LOG=error
    command:
      - --base-path=/data
      - --chain=./chainspecs/raw_spec_finney.json
      - --rpc-external
      - --rpc-cors=all
      - --no-mdns
      - --bootnodes=/dns/bootnode.finney.chain.opentensor.ai/tcp/30333/ws/p2p/12D3KooWRwbMb85RWnT8DSXSYMWQtuDwh4LJzndoRrTDotTR5gDC
      - --sync=warp
      - --database paritydb
      - --db-cache 4096
      - --trie-cache-size 2048

  watchtower:
    image: containrrr/watchtower
    container_name: affine-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 affine-validator affine-runner

volumes:
  grafana-storage:
  validator-cache:
    name: affine-validator-cache
  mainnet-lite-volume:
