version: '3.8'

version: '3.8'

services:
  validator:
    image: thebes1618/affine:latest
    pull_policy: always
    container_name: affine-validator
    restart: unless-stopped
    env_file:
      - .env
      - ~/.affine/config.env
    volumes:
      - ./.env:/app/.env
      - ~/.affine:/root/.affine
      - ~/.bittensor/wallets:/root/.bittensor/wallets
    command: ["-vv", "validate"]

  runner:
    image: thebes1618/affine:latest
    pull_policy: always
    container_name: affine-runner
    restart: unless-stopped
    env_file:
      - .env
      - ~/.affine/config.env
    volumes:
      - ./.env:/app/.env
      - ~/.affine:/root/.affine
      - ~/.bittensor/wallets:/root/.bittensor/wallets
    command: ["-vv", "runner"]

  watchtower:
    image: containrrr/watchtower
    pull_policy: always
    container_name: affine-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 affine-validator affine-runner
