[project]
name = "affine"
version = "0.1.0"
description = "A CLI tool for running evaluations on LLMs"
authors = [{ name = "chutes", email = "founders@chutes.ai" }]
dependencies = [
    "openai",
    "rich",
    "python-dotenv", # Corrected package name
    "pydantic-settings",
    "bittensor",
    "async_lru",
    "botocore",
    "aiobotocore",
    "ipykernel",
    "click",
    "aiohttp",
    "nest-asyncio",
    "ipywidgets>=8.1.7",
]
readme = "README.md"
requires-python = ">=3.8"

[project.scripts]
af = "affine.cli:cli"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["affine"]
exclude = ["results"]
